region_dict = {1: 'Northern Ireland',
               2: 'Scotland',
               3: 'North East',
               4: 'North West',
               5: 'Yorks / Humber',
               6: 'Wales',
               7: 'West Midlands',
               8: 'East Midlands',
               9: 'Anglia',
               10: 'South West',
               11: 'London',
               12: 'South East'
               }

# https://en.wikipedia.org/wiki/Wikipedia:Index_of_United_Kingdom_political_parties_meta_attributes
colours_dict = {'CON': '#0087DC',
                'LAB': '#DC241F',
                'LIB': '#FAA61A',
                'UKIP': '#70147A',
                'Brexit': '#12B6CF',
                'Green': '#6AB023',
                'NAT': '#FEF987',
                'SNP': '#FDF38E',
                'Plaid': '#008142',
                'UUP': '#48A5EE',
                'SDLP': '#3A9E84',
                'DUP': '#D46A4C',
                'SF': '#326760',
                'APNI': '#F6CB2F',
                'CUK': '#222221',
                'ONP': '#4B0082',
                'MIN': '#DDDDDD',
                'OTH': '#DDDDDD',
                'blank':'#EEEEEE33'}